apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "hostpath"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: "hostpath"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/user
    type: DirectoryOrCreate
