apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program

---
apiVersion: v1
kind: Service
metadata:
  name: user-app
  namespace: k8s-program
spec:
  selector:
    app: user-app
  ports:
    - protocol: 'TCP'
      port: 8088
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: userapp-container
          image: epamalesiaskarakhod/userapp-image:1.0.0
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: userName
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-env-config
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-env-config
                  key: port
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 4
            periodSeconds: 3
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
              httpGet:
                path: /actuator/health/readiness
                port: 8080
              initialDelaySeconds: 4
              periodSeconds: 3
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 3
          volumeMounts:
            - name: user-data
              mountPath: /mnt/data
      volumes:
        - name: user-data
          persistentVolumeClaim:
            claimName: users-pvc

