apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---

apiVersion: v1
kind: Service
metadata:
  name: users-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: users-db
  ports:
    - protocol: TCP
      port: {{ .Values.userDB.service.port }}
  clusterIP: None
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: users-db
  namespace: {{ .Values.namespace }}
spec:
  serviceName: users-db
  replicas: {{ .Values.userDB.replicaCount }}
  selector:
    matchLabels:
      app: users-db
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
        - name: users-db
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: userName
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: password
            - name: POSTGRES_DB
              value: usersdb
          envFrom:
            - configMapRef:
                name: initdb
          volumeMounts:
            - name: users-db-data
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/initUserDB.sql
              subPath: initUserDB.sql
          livenessProbe:
            tcpSocket:
              port: {{ .Values.userDB.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: {{ .Values.userDB.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: {{ .Values.userDB.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: users-db-data
          persistentVolumeClaim:
            claimName: users-db-pvc
        - name: initdb
          configMap:
            name: initdb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-db-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "hostpath"
