apiVersion: v1
kind: Service
metadata:
  name: user-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: user-app
  ports:
    - protocol: 'TCP'
      port: 8088
      targetPort: {{ .Values.userApp.service.port }}
  type: {{ .Values.userApp.service.type }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.userApp.replicaCount }}
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: userapp-container
          image: {{ .Values.userApp.image.repository }}
          imagePullPolicy: {{ .Values.userApp.image.pullPolicy }}
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: userName
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: password
            - name: DB_HOST
              value: {{ .Values.userDB.service.host }}
            - name: DB_PORT
              value: "{{ .Values.userDB.service.port }}"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.userApp.service.port }}
            initialDelaySeconds: 4
            periodSeconds: 3
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
              httpGet:
                path: /actuator/health/readiness
                port: {{ .Values.userApp.service.port }}
              initialDelaySeconds: 4
              periodSeconds: 3
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 3
          volumeMounts:
            - name: user-data
              mountPath: /mnt/data
      volumes:
        - name: user-data
          persistentVolumeClaim:
            claimName: users-pvc

