apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program
---

apiVersion: v1
kind: Secret
metadata:
  name: users-db-secret
  namespace: k8s-program
type: Opaque
data:
  userName: cm9vdA==
  password: cGFzc3dvcmQ=
