apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: k8s-program
  labels:
    app.kubernetes.io/name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  ingressClassName: nginx
  rules:
    - host: k8s.ingress.com
      http:
        paths:
            - path: /user-service(/|$)(.*)
              pathType: ImplementationSpecific
              backend:
                service:
                  name: user-app
                  port:
                    number: 8088
            - path: /post-service(/|$)(.*)
              pathType: ImplementationSpecific
              backend:
                service:
                  name: post-app
                  port:
                    number: 8089
