apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-env-config
  namespace: k8s-program
data:
  host: 'posts-db'
  port: '5432'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb
  namespace: k8s-program
data:
  initPostDB.sql: |
    SELECT 'CREATE DATABASE postsdb' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'postsdb');
    \c postsdb;
    CREATE TABLE posts (
      id SERIAL PRIMARY KEY,
      user_id BIGINT NOT NULL,
      text TEXT NOT NULL,
      text TOPIC NOT NULL,
      posted_at DATE NOT NULL
    );