apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb
  namespace: {{ .Values.namespace }}
  labels:
    date: {{ include "post-helm-chart.labels.date" . }}
    version: {{ include "post-helm-chart.labels.version" . }}
data:
  initPostDB.sql: |
    SELECT 'CREATE DATABASE postsdb' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'postsdb');
    \c postsdb;
    CREATE TABLE posts (
      id SERIAL PRIMARY KEY,
      user_id BIGINT NOT NULL,
      text TEXT NOT NULL,
      text TOPIC NOT NULL,
      posted_at DATE NOT NULL
    );