apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}

---

apiVersion: v1
kind: Service
metadata:
  name: post-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: post-app
  ports:
    - protocol: 'TCP'
      port: 8089
      targetPort: {{ .Values.postApp.service.port }}
  type: {{ .Values.postApp.service.type }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.postApp.replicaCount }}
  selector:
    matchLabels:
      app: post-app
  template:
    metadata:
      labels:
        app: post-app
    spec:
      containers:
        - name: postapp-container
          image: {{ .Values.postApp.image.repository }}
          imagePullPolicy: {{ .Values.postApp.image.pullPolicy }}
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: posts-db-secret
                  key: userName
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: posts-db-secret
                  key: password
            - name: DB_HOST
              value: {{ .Values.postDB.service.host }}
            - name: DB_PORT
              value: "{{ .Values.postDB.service.port }}"
            - name: USER_HOST
              value: 'user-app.k8s-program'
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.postApp.service.port }}
            initialDelaySeconds: 4
            periodSeconds: 3
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.postApp.service.port }}
            initialDelaySeconds: 4
            periodSeconds: 3
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3